
#Source : https://leetcode.com/problems/find-the-difference/
#Author : Yuan Wang
#Date   : 2018-07-08
'''
********************************************************************************** 
*Given two strings s and t which consist of only lowercase letters.
*
*String t is generated by random shuffling string s and then add one more letter at a random position.
*
*Find the letter that was added in t.
*
*Example:
*
*Input:
*s = "abcd"
*t = "abcde"
*
*Output:
*e
*
*Explanation:
*'e' is the letter that was added.
**********************************************************************************/
'''

#Self solution, using dictionary Time complexity:O(n) Space complexity:O(n)
def findTheDifferenceA(s, t):
	"""
	:type s: str
	:type t: str
	:rtype: str
	"""
	s_dic=dict(collections.Counter(s))
	t_dic=dict(collections.Counter(t))
	
	for i in t_dic:
		if i not in s_dic:
			return i
		elif t_dic[i] > s_dic[i]:
			return i

#Self solution two using bit manipulation, Time complexity:O(n) Space complexity:O(1)
def findTheDifferenceB(s, t):
	"""
	:type s: str
	:type t: str
	:rtype: str
	"""
	string=s+t
	result=ord(string[0])
	for i in range(1,len(string)):
		result ^= ord(string[i])
	
	return chr(result)


s="abcde"
t="abcdef"
print(findTheDifference(s,t))
